ssh:
  url: bashform.me
  host: 0.0.0.0
  port: 22
  key_path: ./.ssh/id_ed25519

database:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  name: ${POSTGRES_NAME}
