services:
  ssh:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bashform-ssh
    ports:
      - "22:22"
    restart: always
    networks:
      - bashform
networks:
  bashform:
    name: bashform
